# Generated by Django 5.2.8 on 2025-11-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('course', models.CharField()),
                ('experience', models.IntegerField()),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
